### ISSUE TITLE
Uninstalling on Windows does not remove right click context menu entry

### ISSUE THREAD

**Issue by ryancole** [vercel/hyper#1242]
Uninstalling Hyper, on Windows, does not remove the context menu (right click) entry.

**Comment by Speiser** [comment]
Open `\HKEY_CLASSES_ROOT\Directory\Background\shell\` (with regedit) and remove the `Hyper` folder.

**Comment by fyears** [comment]
It seems that it's fixed in version 1.2.1.

I downloaded the latest Windows version today, and **uninstall it from control panel**, the context goes away.

**Comment by secondfry** [comment]
Can confirm as **not** fixed in 1.2.1 (Windows 10, latest updates, Hyper 1.2.1).

**Comment by b-ggs** [comment]
This is still not fixed in 1.3.3.

**Comment by sirberus** [comment]
Still not fixed... Seems small but it leaves a bad taste in my mouth.

**Comment by kamil445** [comment]
For me worked: HKEY_LOCAL_MACHINE\SOFTWARE\Classes\LibraryFolder\background\shell\git_shell and \git_gui

**Comment by BruceBayne** [comment]
They uninstaller do nothing, and leave lots of garbage in registry, thats why i love portable soft,

Try open regedit and just search for 5KPlayer after uninstalling, and you will be shocked

**Comment by shaneknysh** [comment]
may be a duplicate of #3090

**Comment by LabhanshAgrawal** [comment]
Tested on latest canary, seems to be fixed, no results on searching 'Open Hyper here' in registry after uninstall.
